const fs = require('fs');
const s = fs.readFileSync('data/2026-09-08.js', 'utf8');
const body = s.replace(/^[\s\S]*?=\s*/, '').replace(/;\s*$/, '').trim();
const d = eval('(' + body + ')');
console.log('items总数:', d.items.length);
const noImg = d.items.filter(i => !i.image).map(i => i.id);
console.log('缺图条目:', noImg.length ? noImg : '无');
console.log('hero配图:', !!d.hero.image);
const imgs = d.items.map(i => i.image);
const seen = {};
const dup = imgs.filter(v => (seen[v] ? true : (seen[v] = true, false)));
console.log('重复图:', dup.length ? dup : '无');
const removed = ['giant-network-shareholder-reduction','kakao-games-ai-backend','repo-tecs-ecs','tut-unity-perf-guide','ai-ubisoft-farcry7'];
const still = removed.filter(id => d.items.some(i => i.id === id));
console.log('应删未删:', still.length ? still : '无');
console.log('总配图数(含hero):', imgs.length + 1);
